### ISSUE TITLE
IP Address isn't Set Correctly on Gogo Inflight Wifi

### ISSUE THREAD

**Issue by opulencephp** [opulencephp/Opulence#25]
The following exception is thrown when attempting to set the IP address when connected to Gogo inflight wifi:

[Tue Oct 25 06:40:46.203568 2016] [:error] [pid 30215] [client 12.130.117.27:60694] [2016-10-25 10:40:46] application.ERROR: InvalidArgumentException: Invalid host "172.19.131.152, 10.33.185.152" in /var/www/html/project/vendor/opulence/opulence/src/Opulence/Http/Requests/Request.php:399 Stack trace: #0 /var/www/html/project/vendor/opulence/opulence/src/Opulence/Http/Requests/Request.php(345): Opulence\Http\Requests\Request->getHost() #1 /var/www/html/project/vendor/opulence/opulence/src/Opulence/Framework/Http/Middleware/Session.php(63): Opulence\Http\Requests\Request->getFullUrl() #2 [internal function]: Opulence\Framework\Http\Middleware\Session->handle(Object(Opulence\Http\Requests\Request), Object(Closure)) #3 /var/www/html/project/vendor/opulence/opulence/src/Opulence/Pipelines/Pipeline.php(116): call_user_func_array(Array, Array) #4 /var/www/html/project/vendor/opulence/opulence/src/Opulence/Framework/Http/Middleware/CheckMaintenanceMode.php(42): Opulence\Pipelines\Pipeline->Opulence\Pipelines\{closure}(Object(Opulence\Http\Requests\Request)) #5 [internal function]: Opulence\Framework\Http\Middleware\CheckMaintenanceMode->handle(Object(Opulence\Http\Requests\Request), Object(Closure)) #6 /var/www/html/project/vendor/opulence/opulence/src/Opulence/Pipelines/Pipeline.php(116): call_user_func_array(Array, Array) #7 [internal function]: Opulence\Pipelines\Pipeline->Opulence\Pipelines\{closure}(Object(Opulence\Http\Requests\Request)) #8 /var/www/html/project/vendor/opulence/opulence/src/Opulence/Pipelines/Pipeline.php(53): call_user_func(Object(Closure), Object(Opulence\Http\Requests\Request)) #9 /var/www/html/project/vendor/opulence/opulence/src/Opulence/Framework/Http/Kernel.php(116): Opulence\Pipelines\Pipeline->execute() #10 /var/www/html/project/bootstrap/http/start.php(72): Opulence\Framework\Http\Kernel->handle(Object(Opulence\Http\Requests\Request)) #11 [internal function]: {closure}() #12 /var/www/html/project/vendor/opulence/opulence/src/Opulence/Applications/Application.php(102): call_user_func(Object(Closure)) #13 /var/www/html/project/bootstrap/http/start.php(74): Opulence\Applications\Application->start(Object(Closure)) #14 /var/www/html/project/public/index.php(7): require_once('/var/www/html/p...') #15 {main} [] []

**Comment by opulencephp** [comment]
I'm thinking this may be due to Opulence using the X-Forwarded-For header when trying to determine your host.  I may have a fix, but it's difficult to verify it without either a copy of the entire request or at least all the headers sent in the request.
