### ISSUE TITLE
`composer update` after `apex app:rename Project [new_name] causes :flushcache to fail. 

### ISSUE THREAD

**Issue by OddGreg** [opulencephp/Opulence#6]
Ran across this situation while testing.

*Conditions:*
Fresh `composer create-project...`
`apex app:rename Project [new_name]`
`composer update`

*Failure Dump:*

```
PHP Fatal error:  Uncaught Error: Class 'Project\Application\Bootstrappers\Events\DispatcherBootstrapper' not found in /Volumes/Sam/dev/opulence/project/vendor/opulence/opulence/src/Opulence/Bootstrappers/BootstrapperRegistry.php:109
Stack trace:
#0 /Volumes/Sam/dev/opulence/project/vendor/opulence/opulence/src/Opulence/Bootstrappers/Dispatchers/Dispatcher.php(87): Opulence\Bootstrappers\BootstrapperRegistry->resolve('Project\\Applica...')
#1 /Volumes/Sam/dev/opulence/project/vendor/opulence/opulence/src/Opulence/Bootstrappers/Dispatchers/Dispatcher.php(61): Opulence\Bootstrappers\Dispatchers\Dispatcher->dispatchEagerly(Object(Opulence\Bootstrappers\BootstrapperRegistry), Array)
#2 /Volumes/Sam/dev/opulence/project/vendor/opulence/opulence/src/Opulence/Bootstrappers/ApplicationBinder.php(83): Opulence\Bootstrappers\Dispatchers\Dispatcher->dispatch(Object(Opulence\Bootstrappers\BootstrapperRegistry))
#3 [internal function]: Opulence\Bootstrappers\ApplicationBinder->Opulence\Bootstrappers\{closure}()
#4 /Volumes/Sam/dev/opulence in /Volumes/Sam/dev/opulence/project/vendor/opulence/opulence/src/Opulence/Bootstrappers/BootstrapperRegistry.php on line 109

Fatal error: Uncaught Error: Class 'Project\Application\Bootstrappers\Events\DispatcherBootstrapper' not found in /Volumes/Sam/dev/opulence/project/vendor/opulence/opulence/src/Opulence/Bootstrappers/BootstrapperRegistry.php on line 109

Error: Class 'Project\Application\Bootstrappers\Events\DispatcherBootstrapper' not found in /Volumes/Sam/dev/opulence/project/vendor/opulence/opulence/src/Opulence/Bootstrappers/BootstrapperRegistry.php on line 109

Call Stack:
    0.0001     362352   1. {main}() /Volumes/Sam/dev/opulence/project/apex:0
    0.0003     370280   2. require_once('/Volumes/Sam/dev/opulence/project/bootstrap/console/start.php') /Volumes/Sam/dev/opulence/project/apex:3
    0.0061    1158416   3. Opulence\Applications\Application->start() /Volumes/Sam/dev/opulence/project/bootstrap/console/start.php:72
    0.0061    1158416   4. Opulence\Applications\Tasks\Dispatchers\Dispatcher->dispatch() /Volumes/Sam/dev/opulence/project/vendor/opulence/opulence/src/Opulence/Applications/Application.php:106
    0.0061    1158416   5. call_user_func:{/Volumes/Sam/dev/opulence/project/vendor/opulence/opulence/src/Opulence/Applications/Tasks/Dispatchers/Dispatcher.php:34}() /Volumes/Sam/dev/opulence/project/vendor/opulence/opulence/src/Opulence/Applications/Tasks/Dispatchers/Dispatcher.php:34
    0.0061    1158416   6. Opulence\Bootstrappers\ApplicationBinder->Opulence\Bootstrappers\{closure}() /Volumes/Sam/dev/opulence/project/vendor/opulence/opulence/src/Opulence/Applications/Tasks/Dispatchers/Dispatcher.php:34
    0.0063    1173240   7. Opulence\Bootstrappers\Dispatchers\Dispatcher->dispatch() /Volumes/Sam/dev/opulence/project/vendor/opulence/opulence/src/Opulence/Bootstrappers/ApplicationBinder.php:83
    0.0065    1197544   8. Opulence\Bootstrappers\Dispatchers\Dispatcher->dispatchEagerly() /Volumes/Sam/dev/opulence/project/vendor/opulence/opulence/src/Opulence/Bootstrappers/Dispatchers/Dispatcher.php:61
    0.0065    1197600   9. Opulence\Bootstrappers\BootstrapperRegistry->resolve() /Volumes/Sam/dev/opulence/project/vendor/opulence/opulence/src/Opulence/Bootstrappers/Dispatchers/Dispatcher.php:87
`````

**Comment by opulencephp** [comment]
I've reproduced the issue.  Working on a fix.

**Comment by OddGreg** [comment]
Thanks, man.

**Comment by OddGreg** [comment]
Works for me!
